### ISSUE TITLE
feat(app): create app layout template | CU-zndr2a[in-progress]

### ISSUE THREAD

**Issue by Ivan-Ontiveros** [Ivan-Ontiveros/public-dev-portfolio#1]
**TASK:** CU-zndr2a[in-progress]

**APP LAYOUT TEMPLATE SHOULD:**
- [x] 1. render the app w/ a min-height of 100vh
- [x] 2. render a header, main, & footer component
- [x] 3. apply default styling to components
- [x] 4. apply sticky position to header for better SPA smooth-scroll nav UX
- [x] 5. render a wrapper component to contain the SPA's feature sections & abstract the notifications container & the SEO meta data implementation
- [x] 6. render a background image as part of the main component
