### ISSUE TITLE
feature(spa-section): create skills section | CU-zndr0c[in-progress]

### ISSUE THREAD

**Issue by Ivan-Ontiveros** [Ivan-Ontiveros/public-dev-portfolio#5]
**TASK:** CU-zndr0c[in-progress]
**SKILLS SECTION SHOULD:**

- [x] 1. render a section block styled as a card
- [x] 2. render a heading for the main section element
- [x] 3. render card-like components that display arrays of skills grouped by specialty
- [x] 4. render a group of skills for front-end
- [x] 5. render a group of skills for project management (git/github)
- [x] 6. render a group of skills for backend
- [x] 7. be responsive
