### ISSUE TITLE
feature(app): create footer component | CU-yzk3cy[in-progress]

### ISSUE THREAD

**Issue by Ivan-Ontiveros** [Ivan-Ontiveros/public-dev-portfolio#7]
**TASK:** CU-yzk3cy[in-progress]
**Copyright should:**

- [x] 1. render a brand component showing a logo & wordmark
- [x] 2. render a copyright statement
- [x] 3. render a block of icon badges that link to social media platforms
