### ISSUE TITLE
refactor(spa-section): redesign hero section | CU-137m5u2

### ISSUE THREAD

**Issue by Ivan-Ontiveros** [Ivan-Ontiveros/public-dev-portfolio#9]
**TASK:** CU-137m5u2
**HERO REDESIGN SECTION SHOULD:**

- [ ] 1. have an improved heading
- [ ] 2. have an improved subheading
- [ ] 3. shorten the excerpt to communicate my goal
- [ ] 4. render a Call-to-Action button to seamlessly direct visitors to my work
